# Based on https://mesonbuild.com/Continuous-Integration.html
name: SimpleDB CI

on:
  push:
    paths:
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - "**.tpp"
      - "**.ipp"
      - "**.cppm"
  pull_request:
    paths:
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - "**.tpp"
      - "**.ipp"
      - "**.cppm"

jobs:
  build:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@1.3
      - name: Setup Clang
        uses: egor-tensin/setup-clang@1.4
      - name: Install dependendencies
        run: sudo apt install readline-dev
      - name: Configure project
        run: meson setup builddir/
        env:
          CC: gcc
      - name: Build
        run: meson compile -C builddir/
      #- name: Test
      #  run: meson test -C builddir/
      - name: Upload build log
        uses: actions/upload-artifact@4.4.3
        with:
          name: ubuntu-latest_meson_buildlog
          path: builddir/meson-logs/buildlog.txt
